USE CUSTOMER_BEHAVIOUR;


-- 1. TOTAL NO OF CUSTOMERS --
SELECT 
COUNT(*)  AS TOTAL_CUSTOMERS
FROM CUSTOMER_CHURN;

SELECT * FROM CUSTOMER_CHURN;


-- 2. HOW MANY CUSTOMERS HAVE CHURNED --
SELECT
COUNT(*) AS CHURNED_CUSTOMERS
FROM  CUSTOMER_CHURN
WHERE CHURN_LABEL = 'YES';


-- 3. WHAT IS THE OVERALL CHURN_RATE --
SELECT
	COUNT(CASE WHEN  CHURN_LABEL = 'YES' THEN 1 END) * 100.0
	/ COUNT(*) AS CHURN_RATE
FROM CUSTOMER_CHURN;


-- 4. WHAT IS THE CHURN RATE BY CONTRACT TYPE --
SELECT
	CONTRACT,
    COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY CONTRACT 
ORDER BY CHURN_RATE DESC;


-- 5. WHICH PAYMENT METHODS HAS THE HIGHEST CHURN --
SELECT 
	PAYMENT_METHODS,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY PAYMENT_METHODS
ORDER BY CHURN_RATE DESC;


-- 6. DOES TENURE AFFECT CUSTOMER CHURN ? --
SELECT 
CASE
        WHEN TENURE_MONTHS <= 12 THEN '0-12 Months'
        WHEN TENURE_MONTHS <= 24 THEN '13-24 Months'
        WHEN TENURE_MONTHS <= 48 THEN '25-48 Months'
        ELSE '49+ Months'
END AS TENURE_GROUP,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
ROUND(
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY TENURE_GROUP
ORDER BY CHURN_RATE DESC;


-- 7. DOES MONTHLY CHARGE AFFECT CHURN ? --
SELECT 
CASE
        WHEN MONTHLY_CHARGES < 30 THEN 'Low'
        WHEN MONTHLY_CHARGES < 70 THEN 'Medium'
        ELSE 'High'
END AS CHARGE_GROUP,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY CHARGE_GROUP
ORDER BY CHURN_RATE DESC;


-- 8. WHICH INTERNET SERVICE HAS THE HIGHEST CHURN ? --
SELECT 
	INTERNET_SERVICE,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY INTERNET_SERVICE
ORDER BY CHURN_RATE DESC;



-- 9. DOES SENIOR CITIZEN STATUS AFFECT CHURN ? --
SELECT
	SENIOR_CITIZEN,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY SENIOR_CITIZEN
ORDER BY CHURN_RATE DESC;


-- 10. WHAT IS THE CHURN RATE BY GENDER ? --
SELECT
	GENDER,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY GENDER
ORDER BY CHURN_RATE DESC;



-- 11. WHICH CUSROMER SERVICE ARE ASSOCIATED WITH HIGHER CHURN ? --
SELECT
	PHONE_SERVICE,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
	ROUND(
		SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY PHONE_SERVICE
ORDER BY CHURN_RATE DESC;


SELECT * FROM CUSTOMER_CHURN;


-- 12. WHICH CUSTOMER SEGEMENT GENERATES THE HIGHEST REVENUE ? --
SELECT
CONTRACT,
ROUND(SUM(MONTHLY_CHARGES) , 2) AS TOTAL_MONTHLY_REVENUE,
ROUND(AVG(MONTHLY_CHARGES) , 2) AS AVG_MONTHLY_CHARGE
FROM CUSTOMER_CHURN
GROUP BY CONTRACT
ORDER BY TOTAL_MONTHLY_REVENUE DESC;


-- 13. HOW MUCH REVENUE IS ASSOCIATED WITH CHURNED CUSTOMERS ? --
SELECT
ROUND(SUM(MONTHLY_CHARGES) , 2) AS MONTHLY_REVENUE_RISK
FROM CUSTOMER_CHURN
WHERE CHURN_LABEL = 'YES';


-- 14. WHICH CONTRACT AND INTERNET SERVICES COMBINATION HAS THE HIGHEST CHURN ? --
SELECT
CONTRACT,
INTERNET_SERVICE,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) AS CUSTOMER_CHURN,
ROUND(
	SUM( CASE WHEN `CHURN_LABEL` = 'YES' THEN 1 END ) * 100.0 / COUNT(*) , 2) AS CHURN_RATE
FROM CUSTOMER_CHURN
GROUP BY CONTRACT,INTERNET_SERVICE
ORDER BY CHURN_RATE DESC;


SELECT CONTRACT,INTERNET_SERVICE FROM CUSTOMER_CHURN;


SELECT DISTINCT MONTHLY_CHARGES FROM CUSTOMER_CHURN
ORDER BY MONTHLY_CHARGES DESC;


ALTER TABLE CUSTOMER_CHURN
RENAME COLUMN `ï»¿CustomerID` TO CustomerID;


-- 15. WHO ARE HIGH-VALUE CUSTOMERS AT RISK OF CHURN ? --
SELECT 
CUSTOMERID,
CONTRACT,
INTERNET_SERVICE,
TENURE_MONTHS,
MONTHLY_CHARGES,
ROW_NUMBER() OVER(PARTITION BY CONTRACT ORDER BY MONTHLY_CHARGES DESC) AS HIGH_RISK
FROM CUSTOMER_CHURN
WHERE CHURN_LABEL = 'YES'
AND MONTHLY_CHARGES > 80
ORDER BY MONTHLY_CHARGES DESC;

SELECT * FROM CUSTOMER_CHURN;

